export const EVENT_COMMENT_POST_SUCCESS = 'EVENT_COMMENT_POST_SUCCESS';
export const EVENT_COMMENT_POST_ERROR = 'EVENT_COMMENT_POST_ERROR';
export const FETCH_EV_COMMENTS_SUCCESS = 'FETCH_EV_COMMENTS_SUCCESS';
export const FETCH_EV_COMMENTS_ERROR = 'FETCH_EV_COMMENTS_ERROR';
export const DELETE_EV_COMMENT_SUCCESS = 'DELETE_EV_COMMENT_SUCCESS';
export const DELETE_EV_COMMENT_ERROR = 'DELETE_EV_COMMENT_ERROR';
export const EDIT_EV_COMMENT_SUCCESS = 'EDIT_EV_COMMENT_SUCCESS';
export const EDIT_EV_COMMENT_ERROR = 'EDIT_EV_COMMENT_ERROR';
