export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_ERROR = 'UPVOTE_ERROR';
export const REMOVE_UPVOTE_SUCCESS = 'REMOVE_UPVOTE_SUCCESS';
export const REMOVE_UPVOTE_ERROR = 'REMOVE_UPVOTE_ERROR';
export const GET_UPVOTES_SUCCESS = 'GET_UPVOTES_SUCCESS';
export const GET_UPVOTES_ERROR = 'GET_UPVOTES_ERROR';
