export const EVENT_CREATED_SUCCESS = 'EVENT_CREATED_SUCCESS';
export const EVENT_CREATED_ERROR = 'EVENT_CREATED_ERROR';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';
export const FETCH_AUTH_EVENTS = 'FETCH_AUTH_EVENTS';
export const FETCH_AUTH_EVENTS_ERROR = 'FETCH_AUTH_EVENTS_ERROR';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const BEFORE_EVENT_STATE = 'BEFORE_EVENT_STATE';
