export const FETCH_PROFILE = 'FETCH_PROFILE';
export const INIT_PROFILE_SUCCESS = 'INIT_PROFILE_SUCCESS';
export const INIT_PROFILE_ERROR = 'INIT_PROFILE_ERROR';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR';
